---
version: 2

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test

      - publish:
          context: "PyPI account"
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - setup_remote_docker:
          version: stable

      - checkout

      - run:
          name: Run tests
          command: |
            docker build . -t quorumtoolbox
            docker run quorumtoolbox

  publish:

    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}

      - run:
          name: init .pypirc
          command: |
            echo -e "[server-login]" >> ~/.pypirc
            echo -e "username = ${PYPI_USER}" >> ~/.pypirc
            echo -e "password = ${PYPI_PASSWORD}" >> ~/.pypirc

      - run:
          name: create and publish packages
          command: |
            python setup.py sdist bdist_wheel upload
